#note: 'cut_out'
#note: 'test_save_viz'
note: '_SEED_25'
#note: ''
#note: '' #'poisson_mix_training'
# This is when loading the synthetic data, if we want to load a specific one
synthetic_data_note: 'decreased_interpolation_factor_cube_3' 
#'' or 'decreased_interpolation_factor' or 'without_noise'
# =================================== TRAINING SETTINGS ===================================
batch_size: 8

n_experts: 3

spatial_size_x: 32
spatial_size_y: 32
spatial_size_z: 64
spatial_size_t: 24

epochs: 1500

# Optimizer settings
weight_decay: 0.0
beta1: 0.9
beta2: 0.999

# Gradient clipping
max_grad_norm: None

# Factor for dimensions in the latent space
gf_dim: 8

lr: 1.0e-3

do_data_augmentation: False
use_scheduler: False
# How much more the reconstruction loss is weighted 
gen_loss_factor: 100 

z_dim: 2048

# Self-supervised method
# Then use_synthetic_validation must be True
self_supervised: True 
# =================================== DATA SETTINGS ===================================
# Use synthetic data for validation
use_synthetic_validation: True


# Data indexes
idx_start_tr: 0
idx_end_tr: 35
idx_start_vl: 35
idx_end_vl: 42


# If some of the deformations are used in the training, we want to remove them from the validation set give list between which we remove
# Note that we have 7 deformations (None, noisy, deformation, hollwo circle, patch_interpolation, poisson_w_mixing, poisson_wo_mixing)
# Each has 64 slices for 7 patients (total 3136)
# 1792, 2240: Remove patch interpolation
# 2240, 3136: Remove all poisson (with and without mixing)
# 2240, 2688: Remove poisson with mixing
# 2688, 3136: Remove poisson without mixing
# DOUBLE CHECK
indices_to_remove: [2240, 3136]
# If "without_noise" then we have 5 deformations (None, deformation,  patch_interpolation, poisson_w_mixing,poisson_wo_mixing)
## 0, 448: None
## 448, 896: deformation
## 896, 1344: patch_interpolation
## 1344, 1792: poisson_w_mixing
## 1792, 2240: poisson_wo_mixing
## 1344, 2240: Remove all poisson (with and without mixing)


# Metrics to use saving best model (all are always saved/computed)
val_metric: "AP" # AP, auc_roc

# In which format to compute the metric
validation_metric_format: '2Dslice' # "pixelwise" or "2Dslice" or "imagewise"


# =================================== LOGGING SETTINGS ===================================
validation_frequency: 5
training_frequency: 5
training_viz_frequency: 25
validation_viz_frequency: 25



# # =================================== CONTINUE TRAINING ===================================
model_directory : 'logs/vae_convT/masked_slice/20230627-1759_vae_convT_masked_slice_lr1.000e-03-e800-bs8-gf_dim8-daFalse-f100'
model_name : #20230627-1759_vae_convT_masked_slice_lr1.000e-03-e800-bs8-gf_dim8-daFalse-f100
latest_model_epoch : 355

model: 
checkpoint:
continue_training: False
preprocess_method: 