# =================================== TRAINING SETTINGS ===================================
batch_size: 8
init_batches: 64

spatial_size_x: 32
spatial_size_y: 32
spatial_size_z: 64
spatial_size_t: 24


epochs: 71

weight_decay: 0.0
beta1: 0.9
beta2: 0.999


tilt: 160
#box_factor: 0
#bottleneck_factor: 0
z_dim: 256

# Gradient clipping
max_grad_norm: None

lr: 5.0e-5
#lr_decay_begin: 100
#lr_decay_end: 200 # This is the epoch number
#log_freq: 250
#ckpt_freq: 1000
#test_freq: 1000
#drop_prob: 0.1

do_data_augmentation: False
gen_loss_factor: 100 # How much more the reconstruction loss is weighted 

# =================================== DATA SETTINGS ===================================
# Use synthetic data for validation
use_synthetic_validation: False

idx_start_tr: 0
idx_end_tr: 5
idx_start_vl: 5
idx_end_vl: 8


# =================================== LOGGING SETTINGS ===================================
validation_frequency: 10
training_frequency: 10


# # =================================== CONTINUE TRAINING ===================================
model_directory : 'logs/vae/masked_slice/20230601-1713_masked_slice_lr5.000e-05-e1000-bs8-zdim2888-daTrue-f100'
model_name : '20230601-1713_masked_slice_lr5.000e-05-e1000-bs8-zdim2888-daTrue-f100'
latest_model_epoch : 80
model:
checkpoint:
continue_training: False
preprocess_method: 