# =================================== TRAINING SETTINGS ===================================
batch_size: 3
init_batches: 64

spatial_size_x: 144
spatial_size_y: 112
spatial_size_t: 48

epochs: 2


#box_factor: 0
bottleneck_factor: 0
z_dim: 2888

lr: 5.0e-5
lr_decay_begin: 100
#lr_decay_end: 200 # This is the epoch number
log_freq: 250
ckpt_freq: 1000
test_freq: 1000
drop_prob: 0.1

do_data_augmentation: False
gen_loss_factor: 100 # How much more the reconstruction loss is weighted 


# =================================== LOGGING SETTINGS ===================================
validation_frequency: 2


# # =================================== CONTINUE TRAINING ===================================
model_directory : 
model_name : 'test_square'
latest_model_epoch : 
model:
checkpoint:
continue_training:
preprocess_method: