# =================================== TRAINING SETTINGS ===================================
batch_size: 8
init_batches: 64

spatial_size_x: 144
spatial_size_y: 112
spatial_size_t: 48

epochs: 1000

weight_decay: 0.0
beta1: 0.9
beta2: 0.999


#box_factor: 0
bottleneck_factor: 0
z_dim: 2888

lr: 5.0e-5
lr_decay_begin: 100
#lr_decay_end: 200 # This is the epoch number
log_freq: 250
ckpt_freq: 1000
test_freq: 1000
drop_prob: 0.1

do_data_augmentation: True
gen_loss_factor: 200 # How much more the reconstruction loss is weighted 


# =================================== LOGGING SETTINGS ===================================
validation_frequency: 10


# # =================================== CONTINUE TRAINING ===================================
model_directory : 'logs/vae/masked_slice/20230601-1713_masked_slice_lr5.000e-05-e1000-bs8-zdim2888-daTrue-f100'
model_name : '20230601-1713_masked_slice_lr5.000e-05-e1000-bs8-zdim2888-daTrue-f100'
latest_model_epoch : 80
model:
checkpoint:
continue_training: True
preprocess_method: 