#note: 'cut_out'
#note: 'test_save_viz'
#note: 'with_interpolation_training'
#note: '_SEED_10_poisson_mix_training_with_rotation'
#note: '_SEED_10_poisson_mix_training_without_rotation' 
note: '_SEED_15_poisson_mix_training' #poisson_mix_training # _SEED_10_poisson_mix_training


# masked_slice_anomalies_images_from_34_to_41__decreased_interpolation_factor_cube_3
#_without_rotation_without_cs_skip_updated_ao_S10
#_with_rotation_without_cs_skip_updated_ao_S10
#_without_rotation_without_cs 
#_without_some_data_redid_other_version__without_rotation_without_cs_skip_updated_ao_S10
#_without_some_data_redid_other_version__with_rotation_without_cs_skip_updated_ao_S10
#_without_some_data_redid_other_version_with_zeros_with_rotation_without_cs_skip_updated_ao_S10
suffix_data: '_without_rotation_with_cs_skip_updated_ao_S10' 
with_compressed_sensing: False
# Check to make sure SEED is correct in train.py file
synthetic_data_note: '_without_rotation_with_cs_skip_updated_ao_S10_decreased_interpolation_factor_cube_3' # This is when loading the synthetic data, if we want to load a specific one
#'' or 'without_noise_cube_3' or 'decreased_interpolation_factor' or 'without_noise' or 'decreased_interpolation_factor_cube_3' _without_some_data_redid_other_version__without_rotation_without_cs_skip_updated_ao_S10_decreased_interpolation_factor_cube_3
# =================================== TRAINING SETTINGS ===================================
batch_size: 8

spatial_size_x: 32
spatial_size_y: 32
spatial_size_z: 64
spatial_size_t: 24

epochs: 1500

# Optimizer settings
weight_decay: 0.0
beta1: 0.9
beta2: 0.999

# Gradient clipping
max_grad_norm: None

# Factor for dimensions in the latent space
gf_dim: 8

lr: 1.0e-3


do_data_augmentation: False
use_scheduler: False
# How much more the reconstruction loss is weighted 
gen_loss_factor: 100 

# Self-supervised method
# Then use_synthetic_validation must be True
self_supervised: True 

z_dim: 2048
# =================================== DATA SETTINGS ===================================
# Use synthetic data for validation
use_synthetic_validation: True


# Data indexes
idx_start_tr: 0
idx_end_tr: 41
idx_start_vl: 41
idx_end_vl: 51

# If some of the deformations are used in the training, we want to remove them from the validation set give list between which we remove
# Note that we have 7 deformations (None, noisy, deformation, hollwo circle, patch_interpolation, poisson_w_mixing, poisson_wo_mixing)
# Each has 64 slices for 7 patients (total 3136)
# Now we have 10 patients (4480 slices)
# 1792, 2240: Remove patch interpolation 
#- if 10 subjects: 2560,3200
# 2240, 3136: Remove all poisson (with and without mixing) 
#- if 10 subjects: 3200, 4480
# 2240, 2688: Remove poisson with mixing 
#- if 10 subjects: 3200, 3840
# 2688, 3136: Remove poisson without mixing 
#- if 10 subjects: 3840, 4480

# If "without_noise" then we have 5 deformations (None, deformation,  patch_interpolation, poisson_w_mixing,poisson_wo_mixing)
## 0, 448: None 
#- if 10 subjects: 0, 640
## 448, 896: deformation 
#- if 10 subjects: 640, 1280
## 896, 1344: patch_interpolation 
#- if 10 subjects: 1280, 1920
## 1344, 1792: poisson_w_mixing 
#- if 10 subjects: 1920, 2560
## 1792, 2240: poisson_wo_mixing 
#- if 10 subjects: 2560, 3200
## 1344, 2240: Remove all poisson (with and without mixing) 
#- if 10 subjects: 1920, 3200

#indices_to_remove: [3200, 4480] # DOUBLE CHECK (also in utils.py) #if 10 subjets - remove all poisson
#indices_to_remove: [2240, 3136] # DOUBLE CHECK (also in utils.py) #if 7 subjets - remove all poisson
indices_to_remove: [3200, 3840] # Remove Poisson with mix from validation set #if 10 subjets
#indices_to_remove: [2240, 2688] # Remove Poisson with mix from validation set #if 7 subjets
#indices_to_remove: [1280, 1536] # Remove Poisson with mix from validation set #if 4 subjets
#indices_to_remove: [1920, 2688] # DOUBLE CHECK (also in utils.py) #if 6 subjets - remove all poisson
#indices_to_remove: []
# Metrics to use saving best model (all are always saved/computed)
val_metric: "AP" # AP, auc_roc

# In which format to compute the metric
validation_metric_format: '2Dslice' # "pixelwise" or "2Dslice" or "imagewise"


# =================================== LOGGING SETTINGS ===================================
validation_frequency: 5
training_frequency: 5
training_viz_frequency: 25
validation_viz_frequency: 25



# # =================================== CONTINUE TRAINING ===================================
model_directory : 'logs/vae_convT/masked_slice/20230627-1759_vae_convT_masked_slice_lr1.000e-03-e800-bs8-gf_dim8-daFalse-f100'
model_name : #20230627-1759_vae_convT_masked_slice_lr1.000e-03-e800-bs8-gf_dim8-daFalse-f100
latest_model_epoch : #355

model: 
checkpoint:
continue_training: False
preprocess_method: 