
#note: '_poisson_mix_training_with_rotation'
#note: '_poisson_mix_training_without_rotation' 
#note:_all_poisson_tr_val
note: ''
use_wandb: False
seed: 5

# Through selection the following, you decide which dataset to use (as prepared in the preprocessing steps)
include_compressed_sensing_data: True # (Set to True)
use_only_compressed_sensing_data: False # (Set to False)
skip_points_on_centerline: True # Skipping every 2 points on centerline for smoother interpolation (Set to True)
use_updated_ordering_method: True # Using updated method to order points rather than just quadrant based (Set to True)
smoothing: 10 # Smoothing parameter for the interpolation of the centerline (Set to 10)
with_rotation: False # Whether to rotate the vectors with the slices (Set to False)

# This is when loading the synthetic data, if we want to load a specific one
synthetic_data_note: '_decreased_interpolation_factor_cube_3' 
# =================================== TRAINING SETTINGS ===================================
batch_size: 8

spatial_size_x: 32
spatial_size_y: 32
spatial_size_z: 64
spatial_size_t: 24

epochs: 5

# Optimizer settings
weight_decay: 0.0
beta1: 0.9
beta2: 0.999

# Gradient clipping
max_grad_norm: None

# Factor for dimensions in the latent space
gf_dim: 8

lr: 1.0e-3

do_data_augmentation: False
use_scheduler: False
# How much more the reconstruction loss is weighted 
gen_loss_factor: 100 

# How much more the auxiliary loss is weighted 
aux_loss_factor: 0.1
euler_angle_loss_factor: 1

# Self-supervised method
# Then use_synthetic_validation must be True
self_supervised: True 

z_dim: 2048
# =================================== DATA SETTINGS ===================================
# Use synthetic data for validation
use_synthetic_validation: True

# What kind of synthetic data do we introduce on the fly during training
blending:
  method: "mixed_grad"  # Options: "mixed_grad", "source_grad", "interpolation"


# Data indexes
idx_start_tr: 0
idx_end_tr: 41 
idx_start_vl: 41
idx_end_vl: 51

# Deformation Exclusion for Validation Set
# ----------------------------------------
# During training, if some deformations are used, we want to exclude them from the validation set.
# Below are the indices between which different deformations are removed:
#

deformation_list: ['None', 'noisy', 'deformation', 'hollow circle', 'patch_interpolation', 'poisson_with_mixing', 'poisson_without_mixing']


# Metrics to use saving best model (all are always saved/computed)
val_metric: "AP" # AP, auc_roc

# In which format to compute the metric
validation_metric_format: '2Dslice' # "pixelwise" or "2Dslice" or "imagewise"


# =================================== LOGGING SETTINGS ===================================
validation_frequency: 5
training_frequency: 5
training_viz_frequency: 100
validation_viz_frequency: 100



# # =================================== CONTINUE TRAINING ===================================
model_directory : 'Saved_models/simple_conv/masked_slice/20240530-1412_simple_conv_masked_slice_lr1.000e-03-e1500-bs8-gf_dim8-daFalse-f100__SEED_5_2Dslice__without_rotation_with_cs_skip_updated_ao_S10_balanced_decreased_interpolation_factor_cube_3'
latest_model_epoch : 110
# Check best_val_score in the log from previously run model
best_val_score: 0.5
continue_training: False

